FROM nvidia/cuda:10.0-devel-ubuntu18.04

COPY DeePiCt /app/DeePiCt
COPY deploy_local_2D_container.sh /app/DeePiCt/2d_cnn
WORKDIR /app/DeePiCt

# Install necessary packages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update -y && apt-get install -y dialog apt-utils && \
    apt-get install -y build-essential git wget software-properties-common && \
    apt-get update && rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV PATH="/usr/local/miniconda3/bin:${PATH}"
ARG PATH="/usr/local/miniconda3/bin:${PATH}"
RUN cd /tmp  \
    && wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3.sh\
    && bash Miniconda3.sh -b -p /usr/local/miniconda3 \
    && rm -f Miniconda3.sh


# Create environment
RUN conda init bash && \
    conda install -c conda-forge mamba --yes && \
    mamba env create -f /app/DeePiCt/2d_cnn/envs/keras-env.yaml

RUN cd 2d_cnn && \
    ln -s deploy_local_2D_container.sh deepict2D && \
    ln -s deploy_config.sh deepict2D_config

ENV PATH="${PATH}:/app/DeePiCt/2d_cnn"
ARG PATH="${PATH}:/app/DeePiCt/2d_cnn"
