RAW_SUBTOMOGRAMS = "volumes/raw"
LABELED_SUBTOMOGRAMS = "volumes/labels/"
PREDICTED_SEGMENTATION_SUBTOMOGRAMS = "volumes/predictions/"
CLUSTERING_LABELS = "volumes/cluster_labels/"
HDF_INTERNAL_PATH = "MDF/images/0/image"
